#!/usr/bin/env python3

import os
import sys

from analyzer import Analyzer
from termcolor import colored
from helpers import get_user_timeline

def main():

    # ensure proper usage
    if len(sys.argv) != 2:
        sys.exit("Usage: ./tweets @screen_name")
        
    # remove '@' from screen_name if present
    screen_name = sys.argv[1].lstrip("@")
    
    #get tweets
    try:
        tweets = get_user_timeline(screen_name, 50)
    except:
        sys.exit("An unknown error occured")    
    
    if not tweets:
        sys.exit("An unknown error occured")
    
    # absolute paths to lists
    positives = os.path.join(sys.path[0], "positive-words.txt")
    negatives = os.path.join(sys.path[0], "negative-words.txt")

    # instantiate analyzer
    analyzer = Analyzer(positives, negatives)
    
    
    # analyze tweets
    for tweet in tweets:
        score = analyzer.analyze(tweet)
    
        if score > 0.0:
            print(colored(str(score) + " " + tweet, "green"))
        elif score < 0.0:
            print(colored(str(score) + " " + tweet, "red"))
        else:
            print(colored(str(score) + " " + tweet, "yellow"))

if __name__ == "__main__":
    main()